name: Lighthouse

on: push

jobs:
  static-dist-dir:

    runs-on: ubuntu-latest

    steps:
      - name: Run Lighthouse using lighthouserc.json
      - uses: actions/checkout@v2
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: .github/workflows/lighthouserc.json
          temporaryPublicStorage: true
          uploadArtifacts: true

      - name: Run Lighthouse using budget.json
      - uses: actions/checkout@v2
        uses: treosh/lighthouse-ci-action@v2
        with:
          budgetPath: .github/workflows/lighthouse-budget.json
          temporaryPublicStorage: true
          uploadArtifacts: true
