name: Lighthouse
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lighthouserc.json
        uses: treosh/lighthouse-ci-action@v9
        with:
          runs: 3
          configPath: .github/workflows/lighthouserc.json
          temporaryPublicStorage: true
          uploadArtifacts: true
      - name: budget.json
        if: ${{ always() }}
        uses: treosh/lighthouse-ci-action@v9
        with:
          runs: 1
          budgetPath: .github/workflows/lighthouse-budget.json
          configPath: .github/workflows/lighthouserc.json
          temporaryPublicStorage: true
          uploadArtifacts: true
