name: Lighthouse

on: push

jobs:
  static-dist-dir:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Lighthouse using lighthouserc.json
        uses: treosh/lighthouse-ci-action@v3
        with:
          runs: 3
          configPath: .github/workflows/lighthouserc.json
          temporaryPublicStorage: true
          uploadArtifacts: true

      - name: Run Lighthouse using budget.json
        if: ${{ always() }}
        uses: treosh/lighthouse-ci-action@v3
        with:
          runs: 1
          budgetPath: .github/workflows/lighthouse-budget.json
          configPath: .github/workflows/lighthouserc.json
          temporaryPublicStorage: true
          uploadArtifacts: true
